services:
  agent-orchestrator:
    build:
      context: ./agent_orchestrator
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=true
      - BROKER_BASE_URL=http://agent-broker:8000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      agent-broker:
        condition: service_healthy
    networks:
      - agent-network

  agent-broker:
    build:
      context: ./agent_broker
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - DEBUG=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - agent-network

  general-assistant-agent:
    build:
      context: ./agents/general_assistant_agent
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=true
      - BROKER_BASE_URL=http://agent-broker:8000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      agent-broker:
        condition: service_healthy
    networks:
      - agent-network

  tax-agent:
    build:
      context: ./agents/tax_agent
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=true
      - BROKER_BASE_URL=http://agent-broker:8000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      agent-broker:
        condition: service_healthy
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge
