name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==24.3.0 isort==5.13.2 flake8==7.0.0 mypy==1.9.0
        if [ -f agent_discovery/requirements.txt ]; then pip install -r agent_discovery/requirements.txt; fi

    - name: Lint with black
      run: black --check agent_discovery

    - name: Lint with isort
      run: isort --check agent_discovery

    - name: Lint with flake8
      run: flake8 agent_discovery

    - name: Type check with mypy
      run: mypy --exclude 'agent_discovery/tests/' agent_discovery

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint  # Lint 작업이 성공해야 테스트 실행

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f agent_discovery/requirements.txt ]; then pip install -r agent_discovery/requirements.txt; fi

    - name: Test agent_discovery
      run: python -m pytest agent_discovery/tests --cov=agent_discovery --cov-report=term --cov-report=xml:agent_discovery-coverage.xml

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        files: ./agent_discovery-coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false

  build-and-push:
    name: Build and Push Docker Images
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push agent_discovery
      uses: docker/build-push-action@v4
      with:
        context: ./agent_discovery
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/agent_discovery:latest,${{ secrets.DOCKER_HUB_USERNAME }}/agent_discovery:${{ github.sha }}
